[package]
name = "nostr_health_check"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nostr_health_check"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.20"
serde_json = "1.0"
futures-util = "0.3"
reqwest = "0.11"