name: "Release"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.0.0)'
        required: true
        type: string
        default: 'v0.0.0'

# Add concurrency group to cancel redundant workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write
  packages: read

jobs:
  build-linux:
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build_macos.yml
    secrets: inherit

  build-android:
    uses: ./.github/workflows/build_android.yml
    secrets: inherit

  # comment out for now
  # build-ios:
  #   uses: ./.github/workflows/build_ios.yml
  #   secrets: inherit

  create-release:
    needs: [build-linux, build-macos, build-android]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: |
          echo "Artifact contents:"
          ls -R artifacts
          find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          name: White Noise ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            # White Noise ${{ steps.get_version.outputs.VERSION }}

            ## Installation
            ### Desktop
            - **Linux**: Download the .deb, .rpm, or .AppImage file for your distribution
            - **macOS**: Download the .dmg file for your architecture (Intel or Apple Silicon)

            ### Mobile
            - **Android**: Download the .apk file for your device architecture or the universal .aab file
          files: |
            artifacts/**/*
